export const INICIAR_SESION = "INICIAR_SESION";
export const SALIR_SESION = "SALIR_SESION";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const ACTUALIZAR_USUARIO = "ACTUALIZAR_USUARIO";


export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLEAN_SNACKBAR = "CLEAN_SNACKBAR";
